### ISSUE TITLE
Build debian packages for arm64

### ISSUE THREAD

**Issue by russkel** [eProsima/vulcanexus#108]
Hello,

Could you please build `arm64` images for all the vulcanexus packages?

Thanks,

Russ

**Comment by russkel** [comment]
If this is not required at eProsima, could you please open source the scripts you use to build the debians so I can add arm64 support?

**Comment by jsantiago-eProsima** [comment]
Hi @russkel ,

Vulcanexus arm64 debian packages are currently being tested internally. They should be available on the repository in the coming weeks.

**Comment by russkel** [comment]
Hi!

Great news. Thank you.

FYI @natrad100

**Comment by natrad100** [comment]
> Hi!
> 
> Great news. Thank you.
> 
> FYI @natrad100 

Lovey

**Comment by jsantiago-eProsima** [comment]
@russkel Vulcanexus ARM64 packages are now available on the official Vulcanexus repository

**Comment by russkel** [comment]
> @russkel Vulcanexus ARM64 packages are now available on the official Vulcanexus repository

Thanks. We have been using them for a while now.
